#!/usr/bin/env perl

use 5.12.0;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'deps';

use Mojo::Server;
use Gadwall::Util 'bcrypt';

unless (@ARGV && @ARGV >= 2 && @ARGV <= 3) {
    die "$0 <email> <full name> [login]\n";
}

system "stty", "-echo";
print "Password: "; chomp(my $p1 = <STDIN>);
print "\n";
print "Password again: "; chomp(my $p2 = <STDIN>);
print "\n";
system "stty", "echo";

unless ($p1 eq $p2) {
    die "ERROR: Passwords do not match\n";
}

$ENV{MOJO_MODE} = "cli";
my $app = Mojo::Server->new->load_app('./ob');

my @v = (@ARGV, bcrypt($p1));

my $dbh = $app->db;
$dbh->do(<<"SQL", {}, @v) || die $dbh->errstr;
    insert into users (email, name, login, password)
    values (?, ?, ?, ?)
SQL
